[tool.black]
line-length = 80
target_version = ['py38']
exclude = '''
(
    venv
    |\.git
)
'''

[tool.isort]
multi_line_output = 3
force_single_line = true
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 80
known_typing_library = '''
    typing,
    typing_extensions
'''
sections = '''
    FUTURE,
    TYPING_LIBRARY,
    STDLIB,
    THIRDPARTY,
    FIRSTPARTY,
    LOCALFOLDER
'''
skip = '''
venv
'''
